name = "EpiAutoGP"
uuid = "c2940010-6b35-4be1-8bbf-9fa0d9979e50"
authors = ["Sam Brand (USI1) <usi1@cdc.gov>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NowcastAutoGP = "7e9f7f4b-f590-4c14-8324-de4fcbed18f7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
NowcastAutoGP = {rev = "v0.2.0", url = "https://github.com/CDCgov/NowcastAutoGP"}

[compat]
ArgParse = "1.2.0"
CSV = "0.10.15"
DataFramesMeta = "0.15.4"
Dates = "1.11.0"
JSON3 = "1.14.3"
Logging = "1.11.0"
NowcastAutoGP = "0.2.0"
Random = "1.11.0"
Statistics = "1.11.1"
StructTypes = "1.11.0"
Test = "1.11.0"
